services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - DOCKER=true
    volumes:
      - ./php_app:/var/www/html
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: usuarios_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
